version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.15
  pre_build:
    commands:
      - echo Cleaning build files and caches
      - go clean
      - echo running unit tests
      - go ./...
  build:
    commands:
      - echo Build started on `date`
      - go build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - giggle
